const {test}=require('node:test');const assert=require('node:assert/strict');const sharp=require('sharp');
const {FORMAT,composePhoto}=require('../lib/expanded-photo');
test('person pixels appear over generated backdrop without a rectangular original background',async()=>{
 const source=await sharp({create:{width:200,height:150,channels:3,background:'#22aa22'}}).composite([{input:await sharp({create:{width:60,height:120,channels:3,background:'#e02020'}}).png().toBuffer(),left:70,top:30}]).png().toBuffer();
 const alpha=Buffer.alloc(200*150,0);for(let y=30;y<150;y++)for(let x=70;x<130;x++)alpha[y*200+x]=255;
 const rgba=Buffer.alloc(200*150*4);for(let i=0;i<alpha.length;i++){rgba[i*4]=rgba[i*4+1]=rgba[i*4+2]=255;rgba[i*4+3]=alpha[i]}const mask=await sharp(rgba,{raw:{width:200,height:150,channels:4}}).png().toBuffer();
 const backdrop=await sharp({create:{width:FORMAT.width,height:FORMAT.height,channels:3,background:'#1020d0'}}).png().toBuffer();
 const output=await composePhoto(source,mask,{backdrop});assert.equal(output.mode,'person-composite');const info=await sharp(output.jpeg).metadata();assert.equal(info.width,FORMAT.width);assert.equal(info.height,FORMAT.height);
 const edge=await sharp(output.jpeg).extract({left:5,top:5,width:1,height:1}).raw().toBuffer();assert.ok(edge[2]>edge[1]*2);
 const center=await sharp(output.jpeg).extract({left:760,top:550,width:1,height:1}).raw().toBuffer();assert.ok(center[0]>center[2]);
});

test('an inverted mask is corrected and still keeps the person',async()=>{const w=200,h=150;const person=await sharp({create:{width:w,height:h,channels:3,background:'#e02020'}}).png().toBuffer();const bg=await sharp({create:{width:FORMAT.width,height:FORMAT.height,channels:3,background:'#1020d0'}}).png().toBuffer();const rgba=Buffer.alloc(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;rgba[i]=rgba[i+1]=rgba[i+2]=255;rgba[i+3]=(x>=65&&x<135&&y>=25&&y<145)?0:255;}const inverted=await sharp(rgba,{raw:{width:w,height:h,channels:4}}).png().toBuffer();const result=await composePhoto(person,inverted,{backdrop:bg});assert.equal(result.mode,'person-composite');const center=await sharp(result.jpeg).extract({left:760,top:550,width:1,height:1}).raw().toBuffer();assert.ok(center[0]>center[2]);});
test('missing or empty mask keeps the entire original camera image',async()=>{const photo=await sharp({create:{width:640,height:480,channels:3,background:'#d02030'}}).jpeg().toBuffer();for(const mask of [null,await sharp({create:{width:640,height:480,channels:4,background:{r:255,g:255,b:255,alpha:0}}}).png().toBuffer()]){const output=await composePhoto(photo,mask);assert.equal(output.mode,'original-safe');const pixel=await sharp(output.jpeg).extract({left:760,top:550,width:1,height:1}).raw().toBuffer();assert.ok(pixel[0]>pixel[2]);}});
test('safe original preserves a wide camera frame without side cropping',async()=>{const photo=await sharp({create:{width:1600,height:900,channels:3,background:'#902030'}}).jpeg().toBuffer();const output=await composePhoto(photo,null);const m=await sharp(output.jpeg).metadata();assert.equal(output.mode,'original-safe');assert.deepEqual([m.width,m.height],[1536,864]);});
