import {chromium} from 'playwright';import {createServer} from 'node:http';import {readFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const server=createServer(async(req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname;const file=p==='/'?'/index.html':p;const data=await readFile('public'+file);res.setHeader('Content-Type',file.endsWith('.webm')?'video/webm':file.endsWith('.mp4')?'video/mp4':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.glb')?'model/gltf-binary':file.endsWith('.png')?'image/png':'text/html');res.end(data);}catch{res.writeHead(404);res.end();}}).listen(4173);
await mkdir('artifacts',{recursive:true});const browser=await chromium.launch({args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1080,height:1920},permissions:['camera','microphone']});let generated=0,claims=0,release;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/host-sentry.js',r=>r.fulfill({contentType:'text/javascript',body:"export class CameraSentry{constructor(o){this.o=o;this.enabled=false;}async enable(){this.enabled=true;this.o.onStatus('watching');}disable(){this.enabled=false;this.o.onStatus('off');}consume(){}finish(){}}"}));
 await page.route('**/api/read-card',r=>r.fulfill({json:{name:'Test Guest',company:'Test Company',email:'test@example.com',phone:'2025550123',needsReview:true}}));
 await page.route('**/api/host-session',r=>r.fulfill({status:503,json:{error:'Voice unavailable; touch remains available.'}}));
 await page.route('**/api/headshot',async r=>{generated++;assert.ok(r.request().postDataBuffer().includes(Buffer.from(generated===1?'headshot':generated===2?'profile':'banner')),'selected format reaches generation');assert.ok(!r.request().postDataBuffer().includes(Buffer.from('2025550123')),'generation must not wait for or send phone');await new Promise(resolve=>release=resolve);await r.fulfill({contentType:'image/png',headers:{'X-Photo-Id':'mockphoto1234','X-Claim-Token':'mock-capability','X-RPB-Path':'ai-checked','X-Photo-Notice':encodeURIComponent('Please review your headshot.')},body:await readFile('public/assets/logos/rpb.png')});});
 await page.route('**/api/claim-photo',r=>{claims++;const d=r.request().postDataJSON();assert.equal(d.phone,'2025550123');assert.equal(d.confirmed,true);assert.equal(d.likenessApproved,true);return r.fulfill({json:{ok:true,path:'/p/mockphoto1234'}});});
 await page.route('**/api/qr?**',r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')}));
 await page.goto('http://localhost:4173');await page.waitForFunction(()=>document.getElementById('backgroundVideo').currentTime>0,null,{timeout:20000});assert.equal(await page.locator('#backgroundVideo').evaluate(v=>v.muted&&v.loop&&v.playsInline&&v.volume===0),true,'background plays silently inline and loops');await page.screenshot({path:'artifacts/portrait-home.png',fullPage:true});

 await page.locator('#freeNfcButton').click();assert.equal(await page.locator('#nfcDialog').evaluate(d=>d.open),true);
 await page.waitForFunction(()=>document.querySelector('#nfcDialog img').naturalWidth===1280);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile-nfc-qr.png',fullPage:true});
 await page.locator('#closeNfc').click();assert.equal(await page.locator('#nfcDialog').evaluate(d=>d.open),false);
 await page.locator('#freeNfcButton').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#nfcDialog').evaluate(d=>d.open),false);
 assert.equal(await page.locator('#kiosk').getAttribute('data-screen'),'home');await page.setViewportSize({width:1080,height:1920});
 const face=await page.locator('#face').boundingBox();await page.mouse.move(face.x+face.width/2,face.y+face.height/2);await page.mouse.down();await page.waitForTimeout(1100);await page.mouse.up();await page.waitForFunction(()=>document.getElementById('avatarGestureStatus').textContent==='Camera welcome on.');await page.mouse.down();await page.waitForTimeout(1100);await page.mouse.up();assert.equal(await page.locator('#avatarGestureStatus').textContent(),'Camera welcome off.');assert.equal(await page.locator('#formatGrid button').count(),3);assert.equal(await page.locator('#scanStart').isVisible(),false);await page.locator('[data-format=headshot].format-choice').click();await page.locator('#scanStart').click();await page.waitForFunction(()=>!document.getElementById('readCard').disabled);await page.locator('#readCard').click();
 await page.locator('#roleGrid').waitFor({state:'visible'});assert.equal(await page.locator('.role-card').count(),7);
 await page.locator('[data-role=entrepreneur]').click();await page.waitForFunction(()=>!document.getElementById('takePhoto').disabled);
 await page.locator('#takePhoto').click();await page.locator('#cameraBack').click();await page.waitForTimeout(5200);assert.equal(generated,0,'cancelled countdown never generates');
 await page.locator('[data-role=executive]').click();await page.waitForFunction(()=>!document.getElementById('takePhoto').disabled);await page.locator('#takePhoto').click();
 await page.locator('#contactForm').waitFor({state:'visible',timeout:15000});await page.waitForTimeout(100);assert.equal(generated,1,'generation begins before contact confirmation');assert.equal(claims,0);
 assert.equal(await page.locator('#phoneInput').inputValue(),'2025550123');await page.screenshot({path:'artifacts/portrait-contact.png',fullPage:true});
 await page.locator('#voiceButton').click();await page.waitForFunction(()=>document.getElementById('voiceStatus').textContent.includes('unavailable'),{},{timeout:35000});
 assert.equal(await page.locator('#phoneInput').inputValue(),'2025550123','voice failure preserves contact draft');

 await page.locator('#contactConfirm').click();await page.locator('#legalMemory').waitFor({state:'visible'});assert.equal(claims,0);
 assert.equal(await page.locator('.memory-card').count(),12);
 await page.waitForFunction(()=>[...document.querySelectorAll('.memory-front img')].every(i=>i.complete&&i.naturalWidth>=640));
 const ids=await page.locator('.memory-card').evaluateAll(els=>els.map(e=>e.dataset.card));
 const first=0,other=ids.findIndex(id=>id!==ids[0]);
 await page.locator('.memory-card').nth(first).click();await page.locator('.memory-card').nth(other).click();
 assert.equal(await page.locator('#legalMemory').getAttribute('data-locked'),'true');
 const blocked=ids.findIndex((id,i)=>i!==first&&i!==other);await page.locator('.memory-card').nth(blocked).click();
 assert.equal(await page.locator('.memory-card[data-revealed=true]').count(),2,'third tap blocked');
 await page.waitForFunction(()=>document.getElementById('legalMemory').dataset.locked==='false');
 assert.equal(await page.locator('.memory-card[data-revealed=true]').count(),0,'mismatch turns back');
 for(const id of [...new Set(ids)].slice(0,3)){const pair=page.locator('.memory-card[data-card='+id+']');await pair.nth(0).click();await pair.nth(1).click();}
 await page.waitForTimeout(550);
 await page.screenshot({path:'artifacts/portrait-wait.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile-game.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1080,height:1920});
 for(const id of [...new Set(ids)].slice(3)){const pair=page.locator('.memory-card[data-card='+id+']');await pair.nth(0).click();await pair.nth(1).click();}
 assert.equal(await page.locator('#legalMemory').getAttribute('data-matches'),'6');assert.equal(await page.locator('.memory-card:disabled').count(),12);
 await page.locator('[data-memory-reset]').click();assert.equal(await page.locator('#legalMemory').getAttribute('data-matches'),'0');assert.equal(await page.locator('.memory-card[data-revealed=true]').count(),0);

 release();await page.locator('#approvePhoto').waitFor({state:'visible'});assert.equal(claims,0,'QR not claimed before likeness approval');assert.equal(await page.locator('#legalMemory').getAttribute('data-running'),'false','photo reveal stops game');
 assert.equal(await page.locator('#sourceImage').count(),0,'original photo is not displayed');await page.screenshot({path:'artifacts/portrait-review.png',fullPage:true});await page.locator('#approvePhoto').click();await page.locator('#qrImage').waitFor({state:'visible'});assert.equal(claims,1);
 await page.locator('#doneButton').click();assert.equal(await page.locator('#phoneInput').inputValue(),'');assert.equal(await page.locator('#nameInput').inputValue(),'');assert.equal(await page.locator('#resultImage').getAttribute('src'),null);
 await page.setViewportSize({width:390,height:844});await page.reload();await page.screenshot({path:'artifacts/mobile-home.png',fullPage:true});
 await page.locator('[data-format=profile].format-choice').click();await page.locator('#skipCard').click();await page.locator('[data-role=bluecollar]').click();await page.waitForFunction(()=>!document.getElementById('takePhoto').disabled);await page.locator('#takePhoto').click();await page.locator('#contactForm').waitFor({state:'visible'});
 assert.equal(await page.locator('#phoneInput').inputValue(),'');assert.equal(generated,2);release();await page.waitForTimeout(250);assert.equal(await page.locator('#kiosk').getAttribute('data-screen'),'contact','fast image waits for contact confirmation');
 await page.screenshot({path:'artifacts/mobile-contact.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#phoneInput').fill('bad');await page.locator('#contactConfirm').click();assert.equal(claims,1);await page.locator('#phoneInput').fill('2025550123');await page.locator('#contactConfirm').click();await page.locator('#approvePhoto').waitFor({state:'visible'});await page.screenshot({path:'artifacts/mobile-review.png',fullPage:true});
 await page.locator('#resetButton').click();await page.locator('[data-format=banner].format-choice').click();await page.locator('#changeFormat').click();assert.equal(await page.locator('#kiosk').getAttribute('data-screen'),'home');await page.locator('[data-format=banner].format-choice').click();await page.locator('#skipCard').click();await page.locator('[data-role=tech]').click();await page.waitForFunction(()=>!document.getElementById('takePhoto').disabled);await page.locator('#takePhoto').click();await page.locator('#contactForm').waitFor({state:'visible'});await page.waitForTimeout(100);assert.equal(generated,3);release();await page.locator('#phoneInput').fill('2025550123');await page.locator('#contactConfirm').click();await page.locator('#approvePhoto').waitFor({state:'visible'});assert.equal(await page.locator('#kiosk').getAttribute('data-format'),'banner');await page.screenshot({path:'artifacts/mobile-banner-review.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS card-first and skip flows, seven roles, countdown cancel, concurrent generation/contact, voice failure preservation, likeness gate, QR, reset, portrait/mobile (providers mocked).');
}finally{await browser.close();server.close();}
