import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const server=createServer(async(req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname;const file=p==='/'?'/index.html':p;const data=await readFile('public'+file);res.setHeader('Content-Type',file.endsWith('.webm')?'video/webm':file.endsWith('.mp4')?'video/mp4':file.endsWith('.js')||file.endsWith('.mjs')?'text/javascript':file.endsWith('.wasm')?'application/wasm':file.endsWith('.tflite')?'application/octet-stream':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.png')?'image/png':file.endsWith('.jpg')?'image/jpeg':'text/html');res.end(data);}catch{res.writeHead(404);res.end();}}).listen(4173);
await mkdir('artifacts',{recursive:true});const browser=await chromium.launch({args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1080,height:1920},permissions:['camera','microphone']});let generated=0,claims=0,release;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/host-sentry.js',r=>r.fulfill({contentType:'text/javascript',body:"export class CameraSentry{constructor(o){this.o=o;this.enabled=false;}async enable(){this.enabled=true;this.o.onStatus('watching');}disable(){this.enabled=false;this.o.onStatus('off');}consume(){}finish(){}}"}));
 await page.route('**/fixture-person.jpg',async r=>r.fulfill({contentType:'image/jpeg',body:await readFile('tests/fixtures/person.jpg')}));
 await page.route('**/api/host-session',r=>r.fulfill({status:503,json:{error:'Voice unavailable; touch remains available.'}}));
 await page.route('**/api/expanded-photo',async r=>{generated++;assert.ok(r.request().postDataBuffer().includes(Buffer.from('expanded')));await new Promise(resolve=>release=resolve);await r.fulfill({contentType:'image/png',headers:{'X-Photo-Id':'mockphoto1234','X-Claim-Token':'mock-capability','X-RPB-Path':'ai-checked','X-Photo-Notice':encodeURIComponent('Please review your wider photo.')},body:await readFile('public/assets/logos/rpb.png')});});
 await page.route('**/api/claim-photo',r=>{claims++;const d=r.request().postDataJSON();assert.equal(d.phone,undefined);assert.equal(d.likenessApproved,true);assert.equal(d.id,'mockphoto1234');return r.fulfill({json:{ok:true,path:'/p/mockphoto1234?token=mock-view-token'}});});
 await page.route('**/api/qr?**',r=>{const text=new URL(r.request().url()).searchParams.get('text');assert.match(text,/\/p\/mockphoto1234\?token=mock-view-token/);return r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});});
 await page.goto('http://localhost:4173');const segmentation=await page.evaluate(async()=>{const {createPersonMask}=await import('/person-mask.js');const photo=await (await fetch('/fixture-person.jpg')).blob();const mask=await createPersonMask(photo);return {size:mask.size,type:mask.type};});assert.equal(segmentation.type,'image/png');assert.ok(segmentation.size>1000,'person mask is generated in the browser');await page.locator('#formatGrid button').waitFor();assert.equal(await page.locator('#kiosk').evaluate(e=>getComputedStyle(e).backgroundImage.includes('legacycon-home.jpg')),true);assert.equal(await page.locator('#backgroundVideo').isVisible(),false);assert.equal(await page.locator('input[type=tel],#phoneInput').count(),0,'phone entry removed');await page.screenshot({path:'artifacts/portrait-home.png',fullPage:true});
 await page.locator('[data-format=expanded]').click();await page.locator('#camera').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('takePhoto').disabled);assert.equal(await page.locator('.face-guide').count(),0,'head circle removed');assert.equal(await page.locator('#backgroundVideo').isVisible(),true);
 const ratio=await page.locator('#photoFrame').evaluate(frame=>{const video=frame.querySelector('video');return {frame:frame.clientWidth/frame.clientHeight,camera:video.videoWidth/video.videoHeight}});assert.ok(Math.abs(ratio.frame-ratio.camera)<.04,'viewfinder shows full uncropped camera ratio');
 await page.screenshot({path:'artifacts/portrait-camera.png',fullPage:true});await page.locator('#takePhoto').click();await page.locator('#cameraBack').click();await page.waitForTimeout(5200);assert.equal(generated,0,'cancelled countdown never generates');
 await page.locator('[data-format=expanded]').click();await page.waitForFunction(()=>!document.getElementById('takePhoto').disabled);await page.locator('#takePhoto').click();await page.locator('#wait').waitFor({state:'visible',timeout:15000});for(let i=0;i<100&&generated<1;i++)await page.waitForTimeout(50);assert.equal(generated,1);assert.equal(claims,0);assert.equal(await page.locator('#legalMemory .memory-card').count(),20,'Legacy Match has ten pairs');await page.locator('#legalMemory .memory-card').first().click();await page.locator('[data-memory-reset]').click();assert.equal(await page.locator('#legalMemory').getAttribute('data-matches'),'0');await page.screenshot({path:'artifacts/portrait-wait.png',fullPage:true});
 release();await page.locator('#review').waitFor({state:'visible'});assert.equal(await page.locator('#legalMemory').getAttribute('data-running'),'false');assert.equal(claims,0,'QR stays gated until image approval');await page.screenshot({path:'artifacts/portrait-review.png',fullPage:true});await page.locator('#approvePhoto').click();await page.locator('#qrImage').waitFor({state:'visible'});assert.equal(claims,1);assert.equal(await page.locator('#downloadPhoto').count(),0);await page.screenshot({path:'artifacts/portrait-result.png',fullPage:true});
 await page.locator('#doneButton').click();assert.equal(await page.locator('#resultImage').getAttribute('src'),null);assert.equal(await page.locator('#downloadPhoto').count(),0);
 await page.setViewportSize({width:390,height:844});await page.reload();await page.screenshot({path:'artifacts/mobile-home.png',fullPage:true});await page.locator('[data-format=expanded]').click();await page.waitForFunction(()=>!document.getElementById('takePhoto').disabled);await page.screenshot({path:'artifacts/mobile-camera.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#takePhoto').click();await page.locator('#wait').waitFor({state:'visible'});for(let i=0;i<100&&generated<2;i++)await page.waitForTimeout(50);assert.equal(generated,2);await page.screenshot({path:'artifacts/mobile-wait.png',fullPage:true});release();await page.locator('#review').waitFor({state:'visible'});await page.locator('#approvePhoto').click();await page.locator('#qrImage').waitFor({state:'visible'});await page.screenshot({path:'artifacts/mobile-result.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS full-frame booth, memory game, no phone, QR, no kiosk download, reset, portrait/mobile.');
}finally{await browser.close();server.close();}
